### ISSUE TITLE
openstreetmap does not work

### ISSUE THREAD

**Issue by Benleie** [tomickigrzegorz/leaflet-examples#68]
Failed to load resource from openstreetmap
![image](https://github.com/tomickigrzegorz/leaflet-examples/assets/24362871/5eb35ec3-2799-4de7-b4f7-f2fa972abd70)

**Comment by tomickigrzegorz** [comment]
I checked myself and everything works fine
![image](https://github.com/tomickigrzegorz/leaflet-examples/assets/25438490/b890767d-b5fa-41d0-a91d-faabdc498b60)
